name: Actions

on: [ push, pull_request ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 17 needs gradle 7
        java: [ 8, 11, 17, 19 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - run: |
          ./gradlew clean check --refresh-dependencies
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.8.11
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.9.10
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.10.4
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.11.3
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.12.3
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.13.4
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.14.1
          ./gradlew codeCoverageReport

  build:
    name: "Build"
    needs: [ test ]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        java: [ 8, 11, 17, 19 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Execute Gradle build
        run: ./gradlew build

  # Publish
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Publish package
        run: gradle -Prelease publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_SECRET }}
