name: Actions

on: [ push, pull_request ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 17 needs gradle 7
        java: [ 8, 11, 17, 19 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - run: |
          ./gradlew clean check --refresh-dependencies
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.8.11
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.9.10
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.10.4
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.11.3
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.12.3
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.13.4
          ./gradlew clean check --refresh-dependencies -PfasterxmlVersion=2.14.1
          ./gradlew codeCoverageReport

  build:
    name: "Build the project"
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        java: [ 8, 11, 17, 19 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Execute Gradle build
        run: ./gradlew build
